namespace Kable.Generators;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class ProtocolSourceGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Kable.Generators";
    private const string DeviceCommandAttributeName = "DeviceCommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Inject Kable Marker Attributes source
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("KableAttributes.g.cs", SourceText.From(@"// <auto-generated/>
namespace Kable.Generators
{
    using System;

    public interface IDeviceWireCommand
    {
        string FormatWireMessage();
        bool IsUrgent { get; }
    }

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class DeviceCommandAttribute : Attribute
    {
        public string Template { get; }
        public bool IsUrgent { get; set; }
        public DeviceCommandAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class SpontaneousEventAttribute : Attribute
    {
        public string Pattern { get; }
        public SpontaneousEventAttribute(string pattern) => Pattern = pattern;
    }

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class TelemetryEventAttribute : Attribute
    {
        public string Pattern { get; }
        public TelemetryEventAttribute(string pattern) => Pattern = pattern;
    }

    [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
    public sealed class DeviceRpcContractAttribute : Attribute
    {
        public byte Delimiter { get; set; } = 0x0A;
        public bool SupportsCorrelationId { get; set; } = false;
    }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class GeneratedProtocolCodecAttribute : Attribute
    {
        public byte Delimiter { get; set; } = 0x0A;
        public bool SupportsCorrelationId { get; set; } = false;
    }
}
", Encoding.UTF8));
        });

        // 2. Discover Struct / Class annotated with [DeviceCommand]
        var commandDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateType(s),
                transform: static (ctx, _) => GetCommandSemanticTarget(ctx))
            .Where(static m => m != null);

        // 3. Automatically generate partial methods and IDeviceWireCommand implementation code
        context.RegisterSourceOutput(commandDeclarations.Collect(), static (spc, source) =>
        {
            ExecuteCommandGeneration(spc, source!);
        });
    }

    private static bool IsCandidateType(SyntaxNode node)
    {
        return (node is TypeDeclarationSyntax tds) && tds.AttributeLists.Count > 0;
    }

    private static CommandModel? GetCommandSemanticTarget(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == DeviceCommandAttributeName ||
                attr.AttributeClass?.Name == "DeviceCommand")
            {
                string template = attr.ConstructorArguments.Length > 0 
                    ? attr.ConstructorArguments[0].Value?.ToString() ?? "" 
                    : "";

                bool isUrgent = false;
                foreach (var namedArg in attr.NamedArguments)
                {
                    if (namedArg.Key == "IsUrgent" && namedArg.Value.Value is bool b)
                    {
                        isUrgent = b;
                    }
                }

                string typeNamespace = symbol.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : symbol.ContainingNamespace.ToDisplayString();

                string typeKind = symbol.IsRecord 
                    ? (symbol.IsValueType ? "record struct" : "record") 
                    : (symbol.IsValueType ? "struct" : "class");

                var properties = symbol.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Select(p => p.Name)
                    .ToList();

                return new CommandModel(
                    typeNamespace,
                    symbol.Name,
                    typeKind,
                    template,
                    isUrgent,
                    properties);
            }
        }

        return null;
    }

    private static void ExecuteCommandGeneration(SourceProductionContext context, ImmutableArray<CommandModel> commands)
    {
        if (commands.IsDefaultOrEmpty) return;

        foreach (var cmd in commands.Distinct())
        {
            if (cmd == null) continue;

            string formatExpression = GenerateFormatExpression(cmd.Template, cmd.Properties);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated by Kable.Generators />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(cmd.Namespace))
            {
                sb.AppendLine($"namespace {cmd.Namespace}");
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(cmd.Namespace) ? "" : "    ";

            sb.AppendLine($"{indent}partial {cmd.TypeKind} {cmd.TypeName} : global::Kable.Generators.IDeviceWireCommand");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public bool IsUrgent => {(cmd.IsUrgent ? "true" : "false")};");
            sb.AppendLine();
            sb.AppendLine($"{indent}    public string FormatWireMessage()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        return {formatExpression};");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(cmd.Namespace))
            {
                sb.AppendLine("}");
            }

            context.AddSource($"{cmd.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static string GenerateFormatExpression(string template, List<string> propertyNames)
    {
        if (string.IsNullOrEmpty(template)) return "\"\"";

        // Template example: "oBATCH.{ScriptPath}" or "oAPPEND{SampleIndex}" or "oPON"
        if (!template.Contains("{"))
        {
            return $"\"{template}\"";
        }

        // Convert to interpolated string format ($"oBATCH.{ScriptPath}")
        return $"$\"{template}\"";
    }

    private sealed class CommandModel : IEquatable<CommandModel>
    {
        public string Namespace { get; }
        public string TypeName { get; }
        public string TypeKind { get; }
        public string Template { get; }
        public bool IsUrgent { get; }
        public List<string> Properties { get; }

        public CommandModel(
            string @namespace,
            string typeName,
            string typeKind,
            string template,
            bool isUrgent,
            List<string> properties)
        {
            Namespace = @namespace;
            TypeName = typeName;
            TypeKind = typeKind;
            Template = template;
            IsUrgent = isUrgent;
            Properties = properties;
        }

        public bool Equals(CommandModel? other)
        {
            if (other is null) return false;
            return Namespace == other.Namespace && TypeName == other.TypeName;
        }

        public override bool Equals(object? obj) => Equals(obj as CommandModel);
        public override int GetHashCode() => (Namespace + "." + TypeName).GetHashCode();
    }
}
