namespace Kable.Generators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class ProtocolSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Kable Marker Attribute 정의 소스 주입
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("KableAttributes.g.cs", SourceText.From(@"// <auto-generated/>
namespace Kable.Generators
{
    using System;

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class DeviceCommandAttribute : Attribute
    {
        public string Template { get; }
        public bool IsUrgent { get; set; }
        public DeviceCommandAttribute(string template) => Template = template;
    }

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class SpontaneousEventAttribute : Attribute
    {
        public string Pattern { get; }
        public SpontaneousEventAttribute(string pattern) => Pattern = pattern;
    }

    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class TelemetryEventAttribute : Attribute
    {
        public string Pattern { get; }
        public TelemetryEventAttribute(string pattern) => Pattern = pattern;
    }

    [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
    public sealed class DeviceRpcContractAttribute : Attribute
    {
        public byte Delimiter { get; set; } = 0x0A;
        public bool SupportsCorrelationId { get; set; } = false;
    }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class GeneratedProtocolCodecAttribute : Attribute
    {
        public byte Delimiter { get; set; } = 0x0A;
        public bool SupportsCorrelationId { get; set; } = false;
    }
}
", Encoding.UTF8));
        });
    }
}
